### ISSUE TITLE
results

### ISSUE THREAD

**Issue by Cloud-Rambler** [HaotianZhangAI4Science/ResGen#4]
Can you provide us with the results of the samples that were used for evaluation in the paper? thank you!!

**Comment by HaotianZhangAI4Science** [comment]
Sorry to respond late. Since the results are too messy, with almost 1G size. Please leave me your email, and I'm happy to send you a copy.

**Comment by Cloud-Rambler** [comment]
Thanks, my email is wrbwryone@gmail.com!!

**Comment by bbaillif** [comment]
Can you also send me the results ? My email is [bb596@cam.ac.uk](mailto:bb596@cam.ac.uk). Cheers!

**Comment by HaotianZhangAI4Science** [comment]
> Can you also send me the results ? My email is [bb596@cam.ac.uk](mailto:bb596@cam.ac.uk). Cheers!

Done, fell free to contact me if you have any problems!
